-
  name: 'GetPostDetails Query'
  uriPattern: 'get-blog-details'
  methods: ['GET']
  defaults:
    '@package': 'Neos.Demo.BlogApi'
    '@controller': 'Api'
    '@action': 'getPostDetails'

-
  name: 'GetPostListing Query'
  uriPattern: 'get-blog-listing'
  methods: ['GET']
  defaults:
    '@package': 'Neos.Demo.BlogApi'
    '@controller': 'Api'
    '@action': 'getPostListing'
