Neos:
  ContentRepositoryRegistry:
    presets:
      default:
        authProvider:
          factoryObjectName: Neos\ContentRepository\TestSuite\Fakes\FakeAuthProviderFactory
        clock:
          factoryObjectName: Neos\ContentRepository\TestSuite\Fakes\FakeClockFactory
